name = "ftcoa-api"
main = "src/index.js"
workers_dev = true
compatibility_date = "2023-08-23"

[vars]
CORS_ORIGIN = "https://ftcopenalliance.org"

[observability]
enabled = true

[env.dev.vars]
CORS_ORIGIN = "http://localhost:3000"

[[d1_databases]]
binding = "FTCOA_MAIN_DB"
database_id = "47a29a14-1352-4792-b101-8dd8f9a3d245"
database_name = "ftcoa-main"

[[env.dev.d1_databases]]
binding = "FTCOA_MAIN_DB"
database_id = "47a29a14-1352-4792-b101-8dd8f9a3d245"
database_name = "ftcoa-main"

[[r2_buckets]]
binding = 'FTCOA_ARCHIVE'
bucket_name = 'archive'

[[env.dev.r2_buckets]]
binding = 'FTCOA_ARCHIVE'
bucket_name = 'archive'
preview_bucket_name = 'archive'